### ISSUE TITLE
Tint and Shade now in Compass

### ISSUE THREAD

**Issue by robwierzbowski** [at-import/toolkit#12]
I believe the `tint()` and `shade()` functions in Toolkit are identical to the ones now in Compass ([1](https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/colors.rb), [2](http://compass-style.org/reference/compass/helpers/colors/#shade)). Since Toolkit requires Compass, these can probably be removed.

**Comment by Snugug** [comment]
While it's true that `tint()` and `shade()` are both in Compass 0.12, I for the life of me haven't been able to get them to actually work out of the box. Considering they do identical things in identical ways, and I've gotten this one to work, I'm going to keep it in for now. I'll revisit on the next Compass release
