### ISSUE TITLE
Don’t write styles by default

### ISSUE THREAD

**Issue by scottkellum** [at-import/toolkit#13]
Toolkit writes a far amount of CSS by default that can cause problems when importing it into existing projects. Would be nice if styles could be added with something like `@import toolkit; @include toolkit;` instead of just `@import toolkit;`.

**Comment by Snugug** [comment]
When using `@import 'toolkit';` you are importing _all_ of Toolkit, including the partials designed to write styles. There are two partials that do so, the Border Box partial that adds `*, *:before, *:after { @include box-sizing('border-box'); }` and the Fluid Media partial that adds 

```
img, video {
  max-width: 100%;
  height: auto;
}
```

I'm not going to create a mixin to write these styles as that's a bit much, but I'd be willing to consider not automatically importing the Border Box partial. My only concern is this is then a fairly large change that _will_ break CSS using just the normal `@import`.

Are there other styles that are being written other than those two?

**Comment by scottkellum** [comment]
I think thats it. Maybe we should break fluid media down so just the intrinsic ratio can be imported as needed?

**Comment by Snugug** [comment]
I'm OK with splitting Fluid Media into Fluid Media and Intrinsic Ratio, as they are two different things.

**Comment by Snugug** [comment]
Spun Intrinsic Ratio into its own partial, updated gem accordingly.
