### ISSUE TITLE
Triangles Are Broken

### ISSUE THREAD

**Issue by Snugug** [at-import/toolkit#15]
Input Sass:

``` scss
@include triangle(red, 30px, 270);
```

Output CSS

``` css
display: block;
width: 0;
height: 0;
border: 0 solid transparent;
border-bottom-color: red;
border-width: 0 135 30px 135;
```

The border-width property is wrong, and changing the 135s to 135px does not produce the correct triangle,

**Comment by scottkellum** [comment]
`270` is not a compatible measurement for width.

`triangle($color, $height, $width, $angle)`
