### ISSUE TITLE
Broken Behavior path

### ISSUE THREAD

**Issue by yahreen** [at-import/toolkit#19]
When I compile my CSS, I see this broken path for legacy browsers:

```
*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  *behavior: url('/app/assets/css/../behaviors/box-sizing/boxsizing.php');
}
```

Is that supposed to be there?

**Comment by Snugug** [comment]
Yes it is, however it seems as if I forgot to document the install for the behavior. Run `compass install toolkit/box-sizing" one folder back from your CSS directory (a Behaviors folder should be created and be a sibling to your CSS Dir)

**Comment by yahreen** [comment]
I get: `No such framework: "toolkit"`

**Comment by Snugug** [comment]
But… that's not physically possible. You're using toolkit. Are you simply importing the Sass files from a cloned repository, or are you using the Compass extension? If you're using the Compass extension as extensions are designed to be used, then it's physically not possible for you to both be using the extension and for it not to be available.
