### ISSUE TITLE
CodeKit Error on Compile

### ISSUE THREAD

**Issue by yahreen** [at-import/toolkit#3]
I created a new project using the command line:

`compass create <my_project> -r toolkit --using toolkit/susy`

Then load the project into CodeKit.

I then add a line of code into `_design.scss`:

```
a{
   padding:10px;
}
```

and receive this error:

```
Compass was unable to compile one or more files in the project: 

LoadError on line 31 of /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb: no such file to load -- toolkit
Run with --trace to see the full backtrace

(This action was triggered by a change to _design.scss)
```

**Comment by Snugug** [comment]
CodeKit, by default, doesn't use the native Compass compiler and therefore can't find Compass extensions, including Toolkit. Have you made sure that your CodeKit points to your native Compass gem?

**Comment by yahreen** [comment]
I used `gem env path` and set both CodeKit's Compass & Sass paths to my native gems (`/Users/user/.rvm/gems/ruby-1.9.3-p194/gems/...`).

**Comment by Snugug** [comment]
You're using RVM. Do you have Toolkit's gem include in your lock?

**Comment by yahreen** [comment]
Sorry, I'm not familiar with lock files. Should I not use RVM? I'm on OS X Mountain Lion.

Compass.app reports:

```
no such file to load -- toolkit
org/jruby/RubyKernel.java:1033:in `require'
```

**Comment by Snugug** [comment]
If you're new to Ruby, RVM may not be a great tool to get started with because it requires you to know how to lock gems to your project so you can use them. Read up on RVM and once you've figured it out and have tried to add Toolkit to your RVM lock, let me know if you still have the problem.

**Comment by yahreen** [comment]
Can I use Toolkit without RVM?

**Comment by Snugug** [comment]
Yes you can, and you can use it with RVM. The issue you're having appears to be RVM related, not Toolkit related.
