### ISSUE TITLE
Bump Compass version to 0.13.alpha.4

### ISSUE THREAD

**Issue by scottkellum** [at-import/toolkit#30]
I will be bumping the version of Compass to `0.13.alpha.4` because the animation module is required for the carousels. We can either remove the need for the animation modules or we need to bump up our required version of Compass.

So I am bumping the version to `0.13.alpha.4` unless there is any objection.

**Comment by Snugug** [comment]
The reason I didn't was due to not wanting to upset dependency chains until Compass and Sass 3.3 are compatible. Once they are, I'm happy to bump.

In the README for the carousel, i state you need to do it on your own, and no toolkit imports import the carousel

**Comment by scottkellum** [comment]
@Snugug Cool, I will revert. Testing new gem and that was where it was failing.

I should RTFM in the future

**Comment by Snugug** [comment]
For the record, here's the part in the README where this gets stated:
https://github.com/Team-Sass/toolkit/blob/1.x.x/README.md#carousels
