### ISSUE TITLE
Update Nested Context to follow Toolkit Contributing Guidelines

### ISSUE THREAD

**Issue by Snugug** [at-import/toolkit#31]
Nested Context is great, but it does not follow the [Toolkit Contributing Guidelines](https://github.com/Team-Sass/toolkit/blob/1.x.x/CONTRIBUTING.md) in regards to globally setable default arguments or extend options for shared reusable pieces. Please update Nested Context to follow the guidelines.

**Comment by scottkellum** [comment]
Hm, left it local because defaults are far cleaner but will add a global.

**Comment by Snugug** [comment]
Take a look at how Intrinsic Ratio does it. The default is set to a globally defined variable, allowing users to change the default easily

**Comment by scottkellum** [comment]
yup, I know how defaults work.

**Comment by Snugug** [comment]
Sorry, I'm stupid. Going to bed now.

**Comment by scottkellum** [comment]
Added and pushed
