### ISSUE TITLE
Change the image path for SVG Background mixin

### ISSUE THREAD

**Issue by jeremycaldwell** [at-import/toolkit#44]
When using the "SVG Background" mixin I can't seem to get the URL to point to my image correctly when not inline and when using a PNG fallback. The sprites are generated but the paths are incorrect with my structure. 

Everything seems to function correctly but my image path is different and I am getting `background-image: url("/images/logos/menu/iq.svg?1384230060");`

That is correct except I need the path to be "../images" rather than "/images".

I checked the config.rb and I have images_dir = "images" set which is correct. Is there any way to change that through the mixin or elsehwere?

**Comment by Snugug** [comment]
In your `config.rb` file, either set `relative_assets = true` or change `http_path` to be the correct absolute path.

**Comment by jeremycaldwell** [comment]
@Snugug, I set "relative_assets" to "true" and that did the trick. Thanks!
