### ISSUE TITLE
Gem::ImpossibleDependenciesError when installing toolkit

### ISSUE THREAD

**Issue by tomdavies** [at-import/toolkit#47]
I was unsure whether to raise this on this project, as it relates to out-of-sync dependencies across a number of team sass projects.

When I attempt to `gem install toolkit` in a clean/empty gemset I get:

```

ERROR:  While executing gem ... (Gem::ImpossibleDependenciesError)
    compass-0.12.2 requires sass (~> 3.1) but it conflicted:
  Activated sass-3.2.12 instead of (~> 3.3.0.rc.2) via:
    breakpoint-2.3.0, singularitygs-1.1.2, toolkit-1.3.7

```

**Comment by Snugug** [comment]
We're in the process of upgrading everything, but we can't be everywhere at all times. There will be a lag as we go through and update everything. Breakpoint was first, Singularity is next, Toolkit is last.

**Comment by tomdavies** [comment]
@Snugug ok no big deal. 

Are you able to point me toward is a previous (recentish) good set of versions that wouldn't have this dependency conflict? Just trying to get up on an existing project that uses toolkit (without using a Gemfile, :sigh:).

**Comment by Snugug** [comment]
Gotta use a Gemfile, only way you're going to get everything working properly.

Breakpoint 2.1 and current versions of Breakpoint and Singularity should all work together fine.

**Comment by tomdavies** [comment]
Thanks for the quick reply. I know re: Gemfile - other people's code etc.

**Comment by scottkellum** [comment]
rvm is a good way to isolate your environment. I usually use both.

**Comment by tomdavies** [comment]
@scottkellum yep, I'm all over bundler + rvm, just picked this project up from someone else who wasn't but will be by the time I get through with with him in about 30 mins time.
