### ISSUE TITLE
Box-sizing gets added once or twice without any @include

### ISSUE THREAD

**Issue by rpkoller** [at-import/toolkit#48]
Today I wanted to create a stripped down test case to try something in Singularity with placeholder selectors. Thereby i ran into something completely different. ;) 

I've created a test project folder only containing a config.rb file with the following required plugins: 

```
require "sassy-math";          //v1.5 
require "modular-scale";      //v1.0.6
require "breakpoint";           //v2.0.7
require "toolkit";                 //v1.3.8
require "singularitygs";        //v1.1.2
require "singularity-extras";  //v0.0.3
```

Aside that, i've only created a scss folder and a css folder and monitored the whole thing with codekit. Then i've created a a style.scss file with the following  code: 

```
@import 'compass';
@import 'modular-scale';
@import 'singularitygs';
@import 'singularity-extras';
@import 'breakpoint';
@import 'toolkit';
```

which lead to the following css:

```
*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  *behavior: url('../css/../behaviors/box-sizing/boxsizing.php'); }

*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  *behavior: url('../css/../behaviors/box-sizing/boxsizing.php'); }

img, video {
  max-width: 100%;
  height: auto; }
```

the other variants i've tried: 

```
@import 'compass';
@import 'modular-scale';
//@import 'singularitygs';
//@import 'singularity-extras';
@import 'breakpoint';
@import 'toolkit';
```

lead to

```
*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  *behavior: url('../css/../behaviors/box-sizing/boxsizing.php'); }

img, video {
  max-width: 100%;
  height: auto; }
```

The following to variants 

```
@import 'compass';
@import 'modular-scale';
@import 'singularitygs';
@import 'singularity-extras';
@import 'breakpoint';
//@import 'toolkit';
```

```
@import 'compass';
@import 'modular-scale';
//@import 'singularitygs';
//@import 'singularity-extras';
@import 'breakpoint';
//@import 'toolkit';
```

lead to no css output - the expected behaviour i suppose. Cuz basically i've thought Toolkit would require an include (@include box-sizing('border-box');) to apply box-sizing at all or is it regular behaviour? Cheers Ralf

**Comment by rpkoller** [comment]
Hmmm i think i might figured things out. i've changed the order of plugin imports within the scss file:

Before:

```
@import 'compass';
@import 'modular-scale';
@import 'singularitygs';
@import 'singularity-extras';
@import 'breakpoint';
@import 'toolkit';
```

Now:

```
@import 'compass';
@import 'modular-scale';
@import 'toolkit';
@import 'breakpoint';
@import 'singularitygs';
@import 'singularity-extras';
```

Then the border-box definition is only shown once as expected. Sorry for the confusion but haven't read anything warning related regarding the import order of plugins. But makes sense now. :) Best regards Ralf

**Comment by scottkellum** [comment]
Cool, all good now?

you can always use `@import 'toolkit-no-css'` if you don’t want styles written at the top of your stylesheet by default.

**Comment by rpkoller** [comment]
Yeah all good now. Was just a bit puzzled about the behaviour in the first place, but makes total sense now. Oh and i didn't knew about @import 'toolkit-no-css' option. Nice one. Thanks
