### ISSUE TITLE
Error on Toolkit install on Sass 3.2.13 and Compass 0.12.2 - Sass requires Listen ~1.1.0

### ISSUE THREAD

**Issue by rpkoller** [at-import/toolkit#51]
I am running Sass 3.2.13 and Compass 0.12.2 on OSX 10.8.5. with Ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0] and Gem 1.3.6 . I had a few gem issues especially with Modular Scale. Finally lead to a striped down and simple gem set up preceded with a clean install (Just installed Sass/Compass, Breakpoint and Modular Scale):

```
*** LOCAL GEMS ***

breakpoint (2.0.7)
chunky_png (1.2.9)
compass (0.12.2)
fssm (0.2.10)
modular-scale (2.0.0.alpha4)
sass (3.2.13)
```

@scottkellum already helped me over at the modular scale repo to figure things out. One of the only two remaining gems i need is Toolkit. I wanted to install the latest version of Toolki able to run with stable Sass and Compass, like i did with Breakpoint 2.0.7, until the new Sass and Compass versions go final . Unfortunately no matter which version i try to install (1.3.8 oder 1.1.0):

```
sudo gem install toolkit -v 1.x.x
```

i get:

```
ERROR:  Error installing toolkit:
    sass requires listen (~> 1.1.0, runtime)
```

Unable to install toolkit at all. :( Is there a way to get Toolkit running again on stable Sass and Compass? Cuz Listen seems a Sass related gem which wasn't installed along with stable Sass. Best regards Ralf

**Comment by wesgro** [comment]
It seems like the dependencies for the Toolkit --pre option are now applying to 1.3.8 which makes installing it with compass 0.12 and sass 3.2 impossible.
