### ISSUE TITLE
Typo? $ratio != $ration

### ISSUE THREAD

**Issue by starryeyez024** [at-import/toolkit#58]
Sassmeister is automatically using the most recent version of the Toolkit gem, which is 2.0.0.alpha.6. 

My Sass, which worked last week, is now generating the error:
Undefined variable: "$ration".

http://sassmeister.com/gist/starryeyez024/7951177

**Comment by Snugug** [comment]
:( I thought I squashed all of those bugs! In fact, I distinctly remember squashing this bug. I guess not. I'll push an update!
