### ISSUE TITLE
Intrinsic ratio applied to embedded Youtube/Vimeo links not working

### ISSUE THREAD

**Issue by rpkoller** [at-import/toolkit#60]
I've embedded youtube and vimeo links in a Wordpress TinyMCE post. Then i tried to apply an intrinsic ratio to the iframe ( to get the video span 100% of the width and behave fluidly):

```
.news-text > iframe {
    @include intrinsic-ratio(16/9, 100%, 'iframe');
}
```

But no matter what i try 16/9, or 4/3 or 500/281 (the specified extends in the iframe markup), 1.77935942, all the time the video isn't displayed, only the space spanned and freed of other content. would a wrapper be necessary? or isn't the intrinsic ratio working with embedded videos and a solution like fitvids would be necessary? Best regards Ralf

**Comment by Snugug** [comment]
Intrinsic ratios need to be applied to the wrapping element of what you want constrained, not the element itself. If you're getting your embed from within a WYSIWYG post, you're probably going to need to preprocess it to add the needed wrapping element. Read the [README](https://github.com/Team-Sass/toolkit#intrinsic-ratios), the output CSS, and the A List Apart article where they were introduced.

**Comment by rpkoller** [comment]
ahhhh i just thought it would work like with picturefill. there you have the wrapping span containing all the img versions. so i thought the iframe would work as that kind of wrapper too somehow. i guess i presumed too much beforehand. my bad. tried a youtube link with a wrapper now. worked like charm. thanks!
