### ISSUE TITLE
Unable to activate toolkit-2.3.0, because sass-3.2.19 conflicts with sass (~> 3.3.0)

### ISSUE THREAD

**Issue by xzykho** [at-import/toolkit#66]
I cannot find any solutions on how to fix this conflict.

**Comment by Snugug** [comment]
Toolkit 2.x.x requires Sass 3.3.x or higher. If you are using a Gemfile [as recommended](https://github.com/Team-Sass/toolkit#installation), it means you have a Gem dependency somewhere that's incompatible with Sass 3.3, and hence Toolkit isn't working. If you are not using a Gemfile and Bundler, do so.

Please keep in mind that Compass 0.12.x is not compatible with Sass 3.3.x, you need to use Compass 1.0.0.alpha.19 or higher.

**Comment by xzykho** [comment]
Thank you I really appreciate this... I was thinking the same things but I couldn't wrap my head on which ones depends on what.
