### ISSUE TITLE
"intrinsic-ratio" mixin fails without arguments

### ISSUE THREAD

**Issue by lolmaus** [at-import/toolkit#7]
The readme allows using +intrinsic-ratio without arguments:

```
.ratio-16-9 {
  @include intrinsic-ratio;
}
```

But when i do, i receive an error:

```
 error sass/style.sass (Line 27 of _fluid-media.scss: Undefined operation: "1/true times 100%".)
```

To overcome the issue, i have to specify the ratio explicitly, then it works.

**Comment by Snugug** [comment]
That's interesting because I do it all the time. What version of Toolkit are you using? Type in `gem list toolkit` and tell me the highest number you've got installed.

**Comment by lolmaus** [comment]
I've installed it today with "gem install toolkit".

```
$ gem list toolkit

*** LOCAL GEMS ***

toolkit (0.2.1.1, 0.2.0.1, 0.1.18, 0.1.15)
```

Also, i have installed but not included compass-aurora which might have had required a previous version of toolkit?

**Comment by Snugug** [comment]
Nope, you're good. Let me dig in to this. Are you including all of Toolkit or just toolkit/fluid-media?

**Comment by lolmaus** [comment]
Am i doing it right?

`style.sass`:

```
/* First import is: */
@import basic/_libraries.sass

/* Then other imports follow */
```

`basic/_libraries.sass`:

```
@import compass
@import susy
@import toolkit
```

**Comment by Snugug** [comment]
Mostly, your import line should be `@import basic/libraries` but that shouldn't throw the error. I see that you're `libraries` file is SASS formatted, is the file that you're getting the error from SASS or SCSS formatted?

**Comment by lolmaus** [comment]
> Mostly, your import line should be `@import basic/libraries` 

Nah, SASS syntax allows optional underscores, file extensions and single or double quotes.

> is the file that you're getting the error from SASS or SCSS formatted?

It's SASS, you can see that from the error text.

The erroneous line was:

```
+intrinsic-ratio
```

But i'm using Susy that way and it works great.

**Comment by Snugug** [comment]
As does SCSS, but the best practice is to not include the underscore or file extension, but again, this is neither here or there.

I will take a look at the error when I get in to work. There may actually be some functional differences between SASS and SCSS syntax, but I hope not. I'll report back.

**Comment by Snugug** [comment]
I've found the issue, will push out an update when I get to work and have Internet

**Comment by lolmaus** [comment]
Yay! I'm happy that i was helpful to you.

**Comment by Snugug** [comment]
Solved
