### ISSUE TITLE
Diff versions of SASS conflicting

### ISSUE THREAD

**Issue by SiddigZeidan** [at-import/toolkit#70]
Installing the toolkit today, I get this error in the terminal when compass watch:

" Unable to activate toolkit-2.5.2, because sass-3.2.19 conflicts with sass (~> 3.3.0)"

**Comment by Snugug** [comment]
Yup! You should be using [Bundler](http://bundler.io/) to manage your Gem dependencies and Compass version `1.0.0.alpha.20` or greater (as that's the version of Compass compatible with Sass 3.3).

Toolkit 2.x requires Sass 3.3 or higher.
Compass 1.0.0.alpha.x is stable, been using it for a while, pretty much waiting on a handful of changes to Sass to push it out of Alpha IIRC.
