### ISSUE TITLE
font-face mixin collides with identically named mixin from Compass, but with different syntax

### ISSUE THREAD

**Issue by mikl** [at-import/toolkit#76]
Toolkit has a very useful `font-face` mixin, but if you're used to using Compass, you might be used to using [their `@import font-face([…])`](http://compass-style.org/reference/compass/css3/font_face/).

Problem is that the two different versions have different syntax, and if you have both Toolkit and Compass loaded, which one gets used is not quite clear.

So if I use this syntax (which would work with the `font-face` from Compass):

``` scss
@include font-face("Fira Sans", font-files(
  "fira_sans/firasans-book.woff",
  "fira_sans/firasans-book.ttf"
), "fira_sans/firasans-book.eot");
```

I get this error from Toolkit:

> `error sass/print.scss (Line 36 of .vendor/bundle/ruby/2.0.0/gems/toolkit-2.6.0/stylesheets/toolkit/_fonts.scss: $map: (("url('../fonts/fira_sans/firasans-book.woff?1408878462')" "format('woff')"), ("url('../fonts/fira_sans/firasans-book.ttf?1408878462')" "format('truetype')")) is not a map for 'map-has-key')`

I don't really know how this can be handled. Perhaps the Toolkit version could be modified to also work with Compass' `font-files()` structure?

**Comment by Snugug** [comment]
This was done very intentionally to ensure a user is only using one font face mixin. They take different approaches with Toolkit adding additional tooling around `.woff` files.

I will double check that this cannot be accomplished with `font-files` but I'm fairly certain it can't which is why it exists as it does.

In Sass, mixins cascade just like styles. If you import Toolkit after Compass, you'll be using Toolkit's. Other way around? Other way around.

**Comment by mikl** [comment]
Ok, is the syntax for the Toolkit version documented anywhere? I tried doing something like the following, but it doesn't seem to work:

``` scss
@include font-face("Fira Sans", (
  "woff": "fira_sans/firasans-book.woff",
  "ttf": "fira_sans/firasans-book.ttf",
  "eot": "fira_sans/firasans-book.eot"
));
```

(output is this):

``` css
@font-face {
  font-family: "Fira Sans";
  font-weight: normal;
  font-style: normal;
}
```

**Comment by Snugug** [comment]
Like everything else, it's documented [in the README](https://github.com/Team-Sass/toolkit#font-face)

**Comment by Snugug** [comment]
You can also look [at the tests](https://github.com/Team-Sass/toolkit/blob/2.x.x/tests/tests/03-fonts.scss#L31) for an example

**Comment by mikl** [comment]
Sorry to be that guy, but I did look at the README before posting this, and I couldn't figure it out. I'll try taking a look at the tests to see if I can figure it out :)

**Comment by Snugug** [comment]
> `$files` should be a map where the key is the file extensions and the value is the path. If using Compass, paths should be relative to your font directory (`fonts_dir` in `config.rb`).

**Comment by mikl** [comment]
In case someone else is having trouble with the syntax, here's a working example:

``` scss
@include font-face("Fira Sans", (
  'eot': 'fira_sans/firasans-book.eot',
  'woff': 'fira_sans/firasans-book.woff',
  'ttf': 'fira_sans/firasans-book.ttf'
));

@include font-face("Fira Sans", (
  'eot': 'fira_sans/firasans-bold.eot',
  'woff': 'fira_sans/firasans-bold.woff',
  'ttf': 'fira_sans/firasans-bold.ttf'
), bold);
```

**Comment by rocksoup** [comment]
@mikl Thanks you for this comment! I spent way too long trying to figure this out before I found your comment which was exactly what I needed.

**Comment by davo20019** [comment]
Thanks for your comment @mikl
