### ISSUE TITLE
@extend error _fluid-media.scss

### ISSUE THREAD

**Issue by dandineen** [at-import/toolkit#8]
Hi there,

I'm getting an error from LiveReload when I first try and import Toolkit.

I've added require "Toolkit" into my config.rb and added @import "Toolkit" at the top of my screen.scss. When I save this file I get the following error from LiveReload:

error sass/screen.scss (Line 25 of _fluid-media.scss: Invalid CSS after "    @extend ": expected selector_sequence, was "%intrinsic-rati...")

I do have an import for the basic Compass clearfix underneath but removing this stills throws the same error. I don't have a _fluid-media.scss partial either so I have no idea where this error is coming from!

I hope you can help

Regards

Dan

**Comment by dandineen** [comment]
I think I can see what the problem is! LiveReload uses its own version of Sass and Compass - I think they're too old. I'm trying compiling through the CLI and things seem to be working OK.

**Comment by barraponto** [comment]
Yes. Selectors starting with a `%` are placeholder selectors, a new feature from SASS 3.2

**Comment by dandineen** [comment]
That settles that then ;-) Thanks for the help.
