### ISSUE TITLE
Not getting underlines

### ISSUE THREAD

**Issue by mhaagens** [at-import/toolkit#87]
I'm trying to get the underlines to work, but they're not showing up.
The drawing of the background etc. works, but the underline doesn't show up.
If I add text-decoration: underline, the descenders are still hidden my the underline.

`a {
    @include underline(#fff,#000, true, 1, 2, false);
}`

Any tips for me?

**Comment by Snugug** [comment]
You've gotta jiggle with the the distance in like `.1` increments. I used a a default but that changes pretty quickly based on the font you use.
