### ISSUE TITLE
Parallax not working as expected

### ISSUE THREAD

**Issue by josephrexme** [at-import/toolkit#88]
I had sought for a detailed usage guide on the parallax feature but couldn't find one. I went on to try it anyway and I landed at this http://codepen.io/bl4ckdu5t/pen/azqRgN which isn't working

**Comment by scottkellum** [comment]
Hi @bl4ckdu5t, It appears you wrote `@parallax(-2, 1);` and there are two problems with this:
1. The mixin syntax needs to be `@include parallax(-2, 1);`
2. The position of this element will be below the other elements on your page. A positive parallax value may be better like `@include parallax(.5, 1);`. Note that both z-index AND spacial positioning are set here so even if you override z-index to a higher value, the text will probably still be obscured by the other stuff that has a higher `translateZ()` position. Changing `translateZ()` will change how the element parallaxes so you’ll probably not have much luck forcing this to work with a negative value.

**Comment by josephrexme** [comment]
I generally forget to use `@include` most times even with breakpoint. I changed it to a positive parallax value as advised and it's all fine. Thanks
